---
- name: Create Android SDK root directory
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/Android"
    state: directory
    owner: "{{ dev_username }}"
    group: "{{ dev_username }}"
    mode: '0755'
  become: yes

- name: Download Android command-line tools
  ansible.builtin.get_url:
    url: https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
    dest: "/tmp/commandlinetools-linux-latest.zip"
    mode: '0644'
  become: no

- name: "Debug: List contents of command-line tools zip"
  ansible.builtin.command: unzip -l /tmp/commandlinetools-linux-latest.zip
  register: zip_contents
  changed_when: false
  become: no

- name: "Debug: Print zip contents"
  ansible.builtin.debug:
    var: zip_contents.stdout_lines
  changed_when: false

- name: Create temporary directory for command-line tools extraction
  ansible.builtin.file:
    path: "/tmp/android-tools-extract"
    state: directory
    owner: "{{ dev_username }}"
    group: "{{ dev_username }}"
    mode: '0755'
  become: yes

- name: Unarchive command-line tools to temporary location
  ansible.builtin.unarchive:
    src: "/tmp/commandlinetools-linux-latest.zip"
    dest: "/tmp/android-tools-extract"
    remote_src: yes
    owner: "{{ dev_username }}"
    group: "{{ dev_username }}"
  become: yes

- name: Find the top-level extracted directory
  ansible.builtin.find:
    paths: "/tmp/android-tools-extract"
    file_type: directory
    depth: 1
  register: extracted_top_level_dir

- name: Move extracted cmdline-tools to 'latest' subdirectory
  ansible.builtin.command:
    cmd: "mv {{ extracted_top_level_dir.files[0].path }}/* {{ ansible_env.HOME }}/Android/cmdline-tools/latest/"
  args:
    creates: "{{ ansible_env.HOME }}/Android/cmdline-tools/latest/bin/sdkmanager"
  become: yes
  when: extracted_top_level_dir.files | length > 0

- name: Clean up temporary extraction directory
  ansible.builtin.file:
    path: "/tmp/android-tools-extract"
    state: absent
  become: yes

- name: Set ANDROID_HOME and update PATH in .zshrc
  ansible.builtin.blockinfile:
    path: "/home/{{ dev_username }}/.zshrc"
    block: |
      export ANDROID_HOME="{{ ansible_env.HOME }}/Android"
      export PATH="$PATH:$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools"
    marker: "# {mark} ANSIBLE MANAGED BLOCK for Android SDK"
    create: yes
    owner: "{{ dev_username }}"
    group: "{{ dev_username }}"
    mode: '0644'
  become: yes

- name: Install Android SDK components using community.general.android_sdk
  community.general.android_sdk:
    name:
      - "platform-tools"
      - "platforms;android-34"
      - "build-tools;34.0.0"
      - "emulator"
      - "system-images;android-34;default;x86_64"
    sdk_root: "{{ ansible_env.HOME }}/Android"
    accept_licenses: true
    state: present
  become_user: "{{ dev_username }}"
  environment:
    JAVA_HOME: "{{ ansible_env.HOME }}/.sdkman/candidates/java/current" # Use 'current' for SDKMAN
    ANDROID_HOME: "{{ ansible_env.HOME }}/Android"
    PATH: "{{ ansible_env.PATH }}:{{ ansible_env.HOME }}/Android/cmdline-tools/latest/bin:{{ ansible_env.HOME }}/Android/platform-tools"