- hosts: localhost
  become: true
  vars:
    dev_username: "{{ dev_username | default(lookup('env','SUDO_USER') or lookup('env','USER')) }}"
    brew_prefix: "/home/linuxbrew/.linuxbrew"

  roles:
    - role: user
      tags: ['user', 'base']

    - role: sudo
      tags: ['sudo', 'base']
      when: install_sudo_rules | bool

    - role: homebrew
      tags: ['homebrew', 'packages']
      when: install_homebrew | bool

    - role: zsh
      tags: ['zsh', 'shell']
      when: install_zsh | bool

    - role: ohmyzsh
      tags: ['zsh', 'shell']
      when: install_zsh | bool

    - role: starship
      tags: ['starship', 'prompt']
      when: install_starship | bool

    - role: fnm
      tags: ['fnm', 'node', 'packages']
      when: install_node | bool

    - role: bun
      tags: ['bun', 'javascript', 'packages']
      when: install_bun | bool

    - role: biome
      tags: ['biome', 'packages']
      when: install_biome | bool

    - role: sdkman
      tags: ['sdkman', 'packages']
      when: install_sdkman | bool

    - role: snap
      tags: ['snap', 'packages']
      when: install_snap | bool

    - role: kvm
      tags: ['kvm', 'virtualization']
      when: install_kvm | bool

    - role: dotfiles
      tags: ['dotfiles', 'config']
      when: install_dotfiles | bool

    - role: ssh
      tags: ['ssh', 'security']
      when: install_ssh_config | bool


