---
- name: Deploy .aliases
  become_user: "{{ dev_username }}"
  copy:
    src: "{{ role_path }}/files/aliases"
    dest: "/home/{{ dev_username }}/.aliases"
    mode: '0644'

- name: Deploy .gitconfig from template
  become_user: "{{ dev_username }}"
  template:
    src: "{{ role_path }}/templates/gitconfig.j2"
    dest: "/home/{{ dev_username }}/.gitconfig"
    mode: '0644'

- name: Deploy .functions
  become_user: "{{ dev_username }}"
  copy:
    src: "{{ role_path }}/files/functions"
    dest: "/home/{{ dev_username }}/.functions"
    mode: '0644'





