---
- name: Ensure snapd is installed
  ansible.builtin.package:
    name: snapd
    state: present
  become: yes

- name: Install Android Studio via Snap
  community.general.snap:
    name: android-studio
    classic: yes
    state: present
  become: yes
  tags:
    - install
    - android-studio

- name: Create Android SDK directory
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/Android"
    state: directory
    mode: '0755'
  become: no

