---
- name: Install prerequisites for Docker
  ansible.builtin.package:
    name:
      - ca-certificates
      - curl
    state: present
    update_cache: yes
  become: yes

- name: Create directory for APT keyrings
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'
  become: yes

- name: Download Docker GPG key
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/debian/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'
    force: yes
  become: yes

- name: Add Docker APT repository
  ansible.builtin.apt_repository:
    repo: "deb [arch={{ ansible_facts['architecture'] }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian {{ ansible_facts['lsb']['codename'] }} stable"
    state: present
    filename: docker
  become: yes

- name: Install Docker packages
  ansible.builtin.package:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
    update_cache: yes
  become: yes

- name: Add user to docker group
  ansible.builtin.user:
    name: "{{ dev_username }}"
    groups: docker
    append: yes
  become: yes