---
- name: Create config directory for starship
  file:
    path: "/home/{{ dev_username }}/.config"
    state: directory
    owner: "{{ dev_username }}"
    group: "{{ dev_username }}"
    mode: '0755'

- name: Generate Catppuccin Powerline preset for starship
  become_user: "{{ dev_username }}"
  shell: "{{ brew_prefix }}/bin/starship preset catppuccin-powerline -o /home/{{ dev_username }}/.config/starship.toml | cat"
  args:
    executable: /bin/bash

- name: Force Catppuccin Frappe palette in starship config (replace if exists)
  become_user: "{{ dev_username }}"
  replace:
    path: "/home/{{ dev_username }}/.config/starship.toml"
    regexp: "^palette\\s*=\\s*'.*'$"
    replace: "palette = 'catppuccin_frappe'"

- name: Ensure Catppuccin Frappe palette line is present in starship config
  become_user: "{{ dev_username }}"
  lineinfile:
    path: "/home/{{ dev_username }}/.config/starship.toml"
    regexp: "^palette\\s*=\\s*'catppuccin_frappe'$"
    line: "palette = 'catppuccin_frappe'"
    insertafter: EOF

 - name: Ensure add_newline is true in starship config (replace if exists)
  become_user: "{{ dev_username }}"
  replace:
    path: "/home/{{ dev_username }}/.config/starship.toml"
    regexp: "^add_newline\\s*=\\s*.*$"
    replace: "add_newline = true"

 - name: Ensure add_newline line is present in starship config
  become_user: "{{ dev_username }}"
  lineinfile:
    path: "/home/{{ dev_username }}/.config/starship.toml"
    regexp: "^add_newline\\s*=\\s*true$"
    line: "add_newline = true"
    insertafter: BOF

