---
- name: Create config directory for starship
  file:
    path: "/home/{{ dev_username }}/.config"
    state: directory
    owner: "{{ dev_username }}"
    group: "{{ dev_username }}"
    mode: '0755'

- name: Generate Catppuccin Powerline preset for starship
  become_user: "{{ dev_username }}"
  shell: "{{ brew_prefix }}/bin/starship preset catppuccin-powerline -o /home/{{ dev_username }}/.config/starship.toml | cat"
  args:
    executable: /bin/bash

- name: Force Catppuccin Frappe palette in starship config (replace if exists)
  become_user: "{{ dev_username }}"
  replace:
    path: "/home/{{ dev_username }}/.config/starship.toml"
    regexp: "^palette\\s*=\\s*'.*'$"
    replace: "palette = 'catppuccin_frappe'"

- name: Ensure Catppuccin Frappe palette line is present in starship config
  become_user: "{{ dev_username }}"
  lineinfile:
    path: "/home/{{ dev_username }}/.config/starship.toml"
    regexp: "^palette\\s*=\\s*'catppuccin_frappe'$"
    line: "palette = 'catppuccin_frappe'"
    insertafter: EOF

- name: Ensure [line_break] has disabled = false when section exists
  become_user: "{{ dev_username }}"
  replace:
    path: "/home/{{ dev_username }}/.config/starship.toml"
    regexp: "(?ms)(\\[line_break\\][^\\[]*?)^disabled\\s*=\\s*true\\s*$"
    replace: "\\1disabled = false"

- name: Check if [line_break] section exists in starship config
  become_user: "{{ dev_username }}"
  shell: "grep -qxF '[line_break]' /home/{{ dev_username }}/.config/starship.toml"
  register: line_break_section
  changed_when: false
  failed_when: false

- name: Add [line_break] disabled=false section if missing
  become_user: "{{ dev_username }}"
  blockinfile:
    path: "/home/{{ dev_username }}/.config/starship.toml"
    marker: "# {mark} ANSIBLE MANAGED BLOCK line_break"
    block: |
      [line_break]
      disabled = false
    insertafter: EOF
  when: line_break_section.rc != 0

